ReadIT/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReadIT.Models
{
    public class Comment
    {
        [Key]
        public int CommentId { get; set; }

        public int PollId { get; set; }

        [Required(ErrorMessage = "The field 'Comments' cannot be empty.")]
        public string Content { get; set; }

        public string Author { get; set; }

        public DateTime PublicationDate { get; set; }

        public int Votes { get; set; }
    }
}

ReadIT/Models/Poll.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReadIT.Models
{
    public class Poll
    {
        [Key]
        public int PollId { get; set; }

        [Required(ErrorMessage = "The field 'Title' is required.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "The field 'Description' is required.")]
        public string Description { get; set; }

        public PollType PollType { get; set; }

        public int Votes { get; set; }

        public string Author { get; set; }

        public virtual List<Comment> Comments { get; set; }

        [Required(ErrorMessage = "The field 'Content' is required.")]
        public string Content { get; set; }

        public DateTime PublicationDate { get; set; }
    }

    public enum PollType
    {
        Link,
        Text,
        Image,
        Video
    }
}

ReadIT/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReadIT.Models;

namespace ReadIT.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            return View(db.Comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentId,Content,Author")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentId,Content,Author")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReadIT/Controllers/PollsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReadIT.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace ReadIT.Controllers
{
    public class PollsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(string searchString)
        {
            var polls = from p in db.Polls
                         select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                polls = polls.Where(s => s.Title.Contains(searchString));
                return View(polls.ToList());
            }
            return View(db.Polls.ToList());
        }

        // GET: Polls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poll poll = db.Polls.Find(id);
            if (poll == null)
            {
                return HttpNotFound();
            }

            return View(poll);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Details(int? id, FormCollection form)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poll poll = db.Polls.Find(id);
            if (poll == null)
            {
                return HttpNotFound();
            }

            var content = form["Comment"];

            Comment comm = new Comment();
            comm.Content = content;
            comm.Author = User.Identity.Name;
            comm.PollId = poll.PollId;
            comm.Votes = 0;
            comm.PublicationDate = DateTime.Now;

            if (poll.Comments == null)
                poll.Comments = new List<Comment>();

            poll.Comments.Add(comm);

            db.SaveChanges();

            return View(poll);
        }

        // GET: Polls/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Polls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "PollId,Title")] Poll poll)
        {
            if (ModelState.IsValid)
            {
                poll.Author = "";
                poll.Votes = 0;

                db.Polls.Add(poll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(poll);
        }

        // GET: Polls/Create
        [Authorize]
        public ActionResult CreateText()
        {
            return View();
        }

        // POST: Polls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateText([Bind(Include = "PollId,Title,Description,Content")] Poll poll)
        {
            if (ModelState.IsValid)
            {
                poll.Author = User.Identity.GetUserName();
                poll.Votes = 0;
                poll.PollType = PollType.Text;
                poll.PublicationDate = DateTime.Now;

                db.Polls.Add(poll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(poll);
        }

        // GET: Polls/Create
        [Authorize]
        public ActionResult CreateLink()
        {
            Poll poll = new Poll();
            poll.Content = "http://";
            return View(poll);
        }

        // POST: Polls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateLink([Bind(Include = "PollId,Title,Description,Content")] Poll poll)
        {
            if (ModelState.IsValid)
            {
                poll.Author = User.Identity.GetUserName();
                poll.Votes = 0;
                poll.PollType = PollType.Link;
                poll.PublicationDate = DateTime.Now;

                db.Polls.Add(poll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(poll);
        }

        // GET: Polls/Create
        [Authorize]
        public ActionResult CreateImage()
        {
            return View();
        }

        // POST: Polls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateImage([Bind(Include = "PollId,Title,Description")] Poll poll, HttpPostedFileBase file)
        {
            // manually check if model is valid
            bool isValid = false;
            if (poll.PollId != null && poll.Title != null && poll.Description != null)
                isValid = true;

            if (isValid)
            {
                poll.Author = User.Identity.GetUserName();
                poll.Votes = 0;
                poll.PollType = PollType.Image;
                poll.PublicationDate = DateTime.Now;

                // Image file
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);

                    var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    file.SaveAs(path);
                    poll.Content = fileName;
                }
                else
                {
                    return View(poll);
                }

                db.Polls.Add(poll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(poll);
        }

        // GET: Polls/Create
        [Authorize]
        public ActionResult CreateVideo()
        {
            return View();
        }

        // POST: Polls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateVideo([Bind(Include = "PollId,Title,Description,Content")] Poll poll)
        {
            if (ModelState.IsValid)
            {
                poll.Author = User.Identity.GetUserName();
                poll.Votes = 0;
                poll.PollType = PollType.Video;
                poll.PublicationDate = DateTime.Now;

                db.Polls.Add(poll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(poll);
        }

        // GET: Polls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poll poll = db.Polls.Find(id);
            if (poll == null)
            {
                return HttpNotFound();
            }
            return View(poll);
        }

        // POST: Polls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PollId,Title,Votes,Author")] Poll poll)
        {
            if (ModelState.IsValid)
            {
                db.Entry(poll).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(poll);
        }

        // GET: Polls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poll poll = db.Polls.Find(id);
            if (poll == null)
            {
                return HttpNotFound();
            }
            return View(poll);
        }

        // POST: Polls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Poll poll = db.Polls.Find(id);
            db.Polls.Remove(poll);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Polls/PollVote/5
        public void PollVote(int? id, int voteValue, string userName)
        {
            // id - poll Id
            Poll poll = db.Polls.Find(id);

            if (poll != null)
            {
                PollVote pv = db.PollVotes.FirstOrDefault(u => (u.PollId == (int)id) && (u.UserName == userName));

                if (pv == null)
                {
                    pv = new Models.PollVote();
                    db.PollVotes.Add(pv);
                }

                pv.PollId = (int)id;
                pv.UserName = userName;
                if (voteValue > 0)
                    pv.Vote = true;
                else if (voteValue < 0)
                    pv.Vote = false;

ReadIT/Views/Polls/Create.cshtml
@model ReadIT.Models.Poll

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Poll</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })        

        <div id="accordion">
            <h3>Link</h3>
            <div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">URL</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Publish" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <h3>Text</h3>
            <div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Text</label>
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Publish" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <h3>Image</h3>
            <div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" value="Publish" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <h3>Video</h3>
            <div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Publish" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/my_scripts")
}

ReadIT/Views/Polls/CreateImage.cshtml
@model ReadIT.Models.Poll

<h2>Add picture</h2>


@using (Html.BeginForm("CreateImage", "Polls", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Picture</label>            
            <div class="col-md-10">
                <input type="file" name="file" />
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add content" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReadIT/Views/Polls/Delete.cshtml
@model ReadIT.Models.Poll

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Poll</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Votes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Votes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReadIT/Views/Polls/Index.cshtml
@model IEnumerable<ReadIT.Models.Poll>

<!-- Main page -->

@section scripts {
    @if (@User.Identity.IsAuthenticated)
    {
        @Scripts.Render("~/bundles/poll_vote")
    }
    else
    {
        @Scripts.Render("~/bundles/poll_vote_not_logged")
    }
}

<br id="userName" data-username="@User.Identity.Name " />

<!-- Add content buttons -->
<div class="row">
    <a href="@Url.Action("CreateLink", "Polls")" title="Add permalink">
        <div class="col-md-3 btn_link"></div>
    </a>
    <a href="@Url.Action("CreateText", "Polls")" title="Add text">
        <div class="col-md-3 btn_text"></div>
    </a>
    <a href="@Url.Action("CreateImage", "Polls")" title="Add picture">
        <div class="col-md-3 btn_image"></div>
    </a>
    <a href="@Url.Action("CreateVideo", "Polls")" title="Add video">
        <div class="col-md-3 btn_video"></div>
    </a>
</div>
<!-- End of Add content buttons -->

@foreach (var item in Model.OrderByDescending(m => m.PublicationDate))
{
    <br />

    @Html.Partial("_Poll", item)
}

ReadIT/Views/Polls/_Poll.cshtml
@model ReadIT.Models.Poll

<div class="row">
    <div class="col-md-1">
        <div class="row">
            <div class="col-md-6">
                @{
                    var voteValueId = "vote_value" + @Model.PollId;
                }
                <div class="middle_position"><b id=@voteValueId>@Model.Votes</b></div>
            </div>
            <div class="col-md-6" style="padding: 0;">
                @{
                    var idPollVoteUp = "PollVoteUp:" + Model.PollId;
                    var idPollVoteDown = "PollVoteDown:" + Model.PollId;
                }
                <div class="col-md-12 vote_up_btn" id=@idPollVoteUp>
                </div>
                <div class="col-md-12 vote_down_btn" id=@idPollVoteDown>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-10" style="padding: 0;">
        @if (Model.PollType == ReadIT.Models.PollType.Text || Model.PollType == ReadIT.Models.PollType.Link ||
                    Model.PollType == ReadIT.Models.PollType.Video)
        {
            <div class="row">
                <div class="col-md-12">
                    @if (Model.PollType == ReadIT.Models.PollType.Text)
                    {
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                        <a href="@Url.Action("Details", "Polls", new { id = Model.PollId })"><b>@Html.DisplayFor(modelItem => Model.Title)</b></a>
                    }
                    else if (Model.PollType == ReadIT.Models.PollType.Link)
                    {
                        <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                        <a href="@Model.Content"><b>@Html.DisplayFor(modelItem => Model.Title)</b></a>
                    }
                    else if (Model.PollType == ReadIT.Models.PollType.Video)
                    {
                        <span class="glyphicon glyphicon-film" aria-hidden="true"></span>
                        <a href="@Url.Action("Details", "Polls", new { id = Model.PollId })"><b>@Html.DisplayFor(modelItem => Model.Title)</b></a>
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <small>
                        Added by: <span id="Author:@Model.PollId" data-author="@Model.Author" style="color: chocolate;">@Model.Author</span>
                    </small>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @Html.DisplayFor(modelItem => Model.Description)
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @if (Model.Comments == null || Model.Comments.Count == 0)
                    {
                        <a href="@Url.Action("Details", "Polls", new { id = @Model.PollId })#comments"><p><i>Add comment</i></p></a>
                    }
                    else
                    {
                        if (Model.Comments.Count() == 1)
                        {
                            <a href="@Url.Action("Details", "Polls", new { id = @Model.PollId })#comments"><p><i>1 comment</i></p></a>
                        }
                        else
                        {
                            <a href="@Url.Action("Details", "Polls", new { id = @Model.PollId })#comments"><p><i>@Model.Comments.Count() comments</i></p></a>
                        }
                    }
                </div>
            </div>
        }
        else if (Model.PollType == ReadIT.Models.PollType.Image)
        {
            <div class="col-md-1" style="padding: 0;">
                <img src="~/Content/Images/@Model.Content" width="80px" />
            </div>
            <div class="col-md-11">
                <div class="row">
                    <div class="col-md-12">
                        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                        <a href="~/Content/Images/@Model.Content"><b>@Html.DisplayFor(modelItem => Model.Title)</b></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <small>
                            Added by: <span id="Author:@Model.PollId" data-author="@Model.Author" style="color: chocolate;">@Model.Author</span>
                        </small>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.DisplayFor(modelItem => Model.Description)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @if (Model.Comments == null || Model.Comments.Count == 0)
                        {
                            <a href="@Url.Action("Details", "Polls", new { id = @Model.PollId })#comments"><p><i>Add comment</i></p></a>
                        }
                        else
                        {
                            if (Model.Comments.Count() == 1)
                            {
                                <a href="@Url.Action("Details", "Polls", new { id = @Model.PollId })#comments"><p><i>1 comment</i></p></a>
                            }
                            else
                            {
                                <a href="@Url.Action("Details", "Polls", new { id = @Model.PollId })#comments"><p><i>@Model.Comments.Count() comments</i></p></a>
                            }
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>